from django.urls import path
from . import views

app_name = 'analytics'

urlpatterns = [
    path('', views.index, name='index'),
    path('mobile/', views.mobile_notice, name='mobile_notice'),
    path('account/', views.account_view, name='account'),
    path('posts/', views.posts_view, name='posts'),
    path('posts/run/', views.run_extraction, name='run_extraction'),
    path('posts/save/', views.save_content_set, name='save_content_set'),
    path('posts/delete-items/', views.delete_items, name='delete_items'),
    path('posts/refresh-posts/', views.refresh_posts, name='refresh_posts'),
    path('posts/download-click-viz/', views.download_click_visualization, name='download_click_visualization'),
    path('posts/download-annotated/', views.download_annotated_posts, name='download_annotated_posts'),
    path('posts/download-csv/', views.download_extracted_csv, name='download_extracted_csv'),
    path('posts/process/', views.run_processing, name='run_processing'),
    path('posts/review/approve/', views.approve_post, name='approve_post'),
    path('posts/review/reprocess/', views.reprocess_post, name='reprocess_post'),
    path('posts/save-template/', views.save_processing_template, name='save_processing_template'),
    path('posts/load-templates/', views.load_processing_templates, name='load_processing_templates'),
    path('posts/delete-template/<int:template_id>/', views.delete_processing_template, name='delete_processing_template'),
    path('posts/clear-processed/', views.clear_processed_posts, name='clear_processed_posts'),
    path('posts/load-processed/<str:post_id>/', views.load_processed_post, name='load_processed_post'),
    path('insights/', views.insights_view, name='insights'),
    path('insights/load-processed-data/', views.load_processed_data, name='load_processed_data'),
    path('insights/load-content-set/<str:set_name>/', views.load_content_set, name='load_content_set'),
    path('insights/generate-section-insights/', views.generate_section_insights, name='generate_section_insights'),
    path('insights/save-section-report/', views.save_section_report, name='save_section_report'),
    path('insights/load-section-report/', views.load_section_report, name='load_section_report'),
    path('insights/delete-section-reports/', views.delete_section_reports, name='delete_section_reports'),
    path('insights/section-report-status/', views.get_section_report_status, name='get_section_report_status'),
    path('insights/report-status/<uuid:task_id>/', views.report_status, name='report_status'),
    path('insights/download-csv/<str:set_name>/', views.download_csv, name='download_csv'),
    path('insights/rename-set/', views.rename_set, name='rename_set'),
    path('insights/copy-set/', views.copy_set, name='copy_set'),
    path('insights/merge-sets/', views.merge_sets, name='merge_sets'),
    path('insights/delete-items/', views.delete_items_from_set, name='delete_items_from_set'),
    path('insights/delete-set/', views.delete_set, name='delete_set'),
    path('survey/submit/', views.submit_survey, name='submit_survey'),
    path('cron/click-viz-status/', views.cron_status, name='cron_status'),
]
