# Generated by Django - Initial migration for analytics app

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(help_text='Beehiiv post ID', max_length=255, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('subtitle', models.TextField(blank=True, null=True)),
                ('publish_date_cst', models.DateField()),
                ('recipients', models.IntegerField(default=0)),
                ('delivered', models.IntegerField(default=0)),
                ('email_opens', models.IntegerField(default=0)),
                ('unique_email_opens', models.IntegerField(default=0)),
                ('email_clicks', models.IntegerField(default=0)),
                ('unique_email_clicks', models.IntegerField(default=0)),
                ('unsubscribes', models.IntegerField(default=0)),
                ('spam_reports', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-publish_date_cst'],
            },
        ),
        migrations.CreateModel(
            name='ContentSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional description of this content set')),
                ('items_data', models.JSONField(help_text='JSON data containing the extracted items')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-publish_date_cst'], name='analytics_p_publish_d47c8a_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['post_id'], name='analytics_p_post_id_4e1a9d_idx'),
        ),
    ]
