# Generated by Django 5.2.8 on 2025-12-02 02:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "report_text",
                    models.TextField(help_text="The markdown-formatted report content"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.RenameIndex(
            model_name="post",
            new_name="analytics_p_publish_2615cc_idx",
            old_name="analytics_p_publish_d47c8a_idx",
        ),
        migrations.RenameIndex(
            model_name="post",
            new_name="analytics_p_post_id_f80d3d_idx",
            old_name="analytics_p_post_id_4e1a9d_idx",
        ),
        migrations.AddField(
            model_name="report",
            name="content_set",
            field=models.ForeignKey(
                help_text="The content set this report is based on",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reports",
                to="analytics.contentset",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="report",
            unique_together={("name", "content_set")},
        ),
    ]
