# Generated by Django 5.2.8 on 2025-12-11 03:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0002_report_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="status",
            field=models.CharField(
                default="Published", help_text="Draft or Published", max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="publish_date_cst",
            field=models.DateField(blank=True, null=True),
        ),
    ]
