# Generated by Django 5.2.8 on 2025-12-11 03:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0003_add_status_and_nullable_publish_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="creation_date",
            field=models.DateTimeField(
                blank=True,
                help_text="When the post was first created in Beehiiv",
                null=True,
            ),
        ),
    ]
