# Generated by Django 5.2.8 on 2025-12-11 22:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0004_add_creation_date"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UsageAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "monthly_quota",
                    models.PositiveIntegerField(
                        default=100000, help_text="Token quota per month"
                    ),
                ),
                (
                    "used_this_period",
                    models.PositiveIntegerField(
                        default=0, help_text="Tokens used in current billing period"
                    ),
                ),
                (
                    "period_start",
                    models.DateField(help_text="Start of current billing period"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_account",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Usage Account",
                "verbose_name_plural": "Usage Accounts",
            },
        ),
    ]
