# Generated by Django 5.2.8 on 2025-12-12 04:36

import analytics.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0006_add_beehiiv_credentials"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usageaccount",
            name="monthly_quota",
            field=models.PositiveIntegerField(
                default=analytics.models.get_default_monthly_credits,
                help_text="Credits available per month",
            ),
        ),
        migrations.AlterField(
            model_name="usageaccount",
            name="used_this_period",
            field=models.PositiveIntegerField(
                default=0, help_text="Credits used in current billing period"
            ),
        ),
    ]
