# Generated by Django 5.2.8 on 2025-12-12 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0007_alter_usageaccount_monthly_quota_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Publication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pub_id",
                    models.CharField(
                        help_text="Beehiiv publication ID", max_length=255, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "organization_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="usageaccount",
            name="api_key_valid",
            field=models.BooleanField(
                default=False,
                help_text="Whether the API key has been validated against Beehiiv",
            ),
        ),
        migrations.AddField(
            model_name="usageaccount",
            name="available_publications",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Cached list of publications from Beehiiv API",
            ),
        ),
        migrations.AlterField(
            model_name="contentset",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AddField(
            model_name="contentset",
            name="publication",
            field=models.ForeignKey(
                blank=True,
                help_text="The publication this content set belongs to",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="content_sets",
                to="analytics.publication",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="publication",
            field=models.ForeignKey(
                blank=True,
                help_text="The publication this post belongs to",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="posts",
                to="analytics.publication",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="contentset",
            unique_together={("name", "publication")},
        ),
    ]
