# Generated by Django 5.2.8 on 2025-12-12 21:46

from django.db import migrations


def assign_existing_data_to_publication(apps, schema_editor):
    """
    Assign all existing Posts and ContentSets to the publication from .env.
    """
    Publication = apps.get_model('analytics', 'Publication')
    Post = apps.get_model('analytics', 'Post')
    ContentSet = apps.get_model('analytics', 'ContentSet')

    # Publication ID from .env
    pub_id = 'pub_08dedd8f-238f-47dc-ac1c-5cb874817a91'
    pub_name = 'Building AI Agents'

    # Create or get the publication
    publication, created = Publication.objects.get_or_create(
        pub_id=pub_id,
        defaults={'name': pub_name, 'organization_name': 'Functional Media'}
    )

    # Assign all orphan posts to this publication
    Post.objects.filter(publication__isnull=True).update(publication=publication)

    # Assign all orphan content sets to this publication
    ContentSet.objects.filter(publication__isnull=True).update(publication=publication)


def reverse_assignment(apps, schema_editor):
    """Reverse: set publication to null for all posts and content sets."""
    Post = apps.get_model('analytics', 'Post')
    ContentSet = apps.get_model('analytics', 'ContentSet')

    Post.objects.all().update(publication=None)
    ContentSet.objects.all().update(publication=None)


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0008_publication_and_api_validation"),
    ]

    operations = [
        migrations.RunPython(assign_existing_data_to_publication, reverse_assignment),
    ]
