# Generated by Django 4.2.27 on 2025-12-22 04:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("analytics", "0010_add_user_to_post_and_contentset"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExecutionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ts_start", models.DateTimeField(help_text="When execution started")),
                ("ts_end", models.DateTimeField(help_text="When execution ended")),
                (
                    "duration_ms",
                    models.IntegerField(help_text="Duration in milliseconds"),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("request", "HTTP Request"),
                            ("function", "Function Call"),
                        ],
                        help_text="Type of log entry",
                        max_length=20,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="View name or module.function", max_length=255
                    ),
                ),
                (
                    "success",
                    models.BooleanField(
                        default=True, help_text="Whether execution succeeded"
                    ),
                ),
                (
                    "error_type",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Exception class name",
                        max_length=255,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, default="", help_text="Exception message"
                    ),
                ),
                (
                    "traceback",
                    models.TextField(
                        blank=True, default="", help_text="Full traceback if error"
                    ),
                ),
                (
                    "request_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="UUID for request correlation",
                        max_length=64,
                    ),
                ),
                (
                    "parent_id",
                    models.BigIntegerField(
                        blank=True,
                        help_text="ID of parent log entry for nesting",
                        null=True,
                    ),
                ),
                (
                    "inputs",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Input parameters (placeholder)",
                    ),
                ),
                (
                    "outputs",
                    models.JSONField(
                        blank=True, default=dict, help_text="Output data (placeholder)"
                    ),
                ),
                (
                    "meta",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional metadata (placeholder)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who triggered the execution",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="execution_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="analytics_e_created_0ab321_idx"
                    ),
                    models.Index(
                        fields=["kind", "name"], name="analytics_e_kind_87e0f0_idx"
                    ),
                    models.Index(
                        fields=["request_id"], name="analytics_e_request_b027fc_idx"
                    ),
                    models.Index(
                        fields=["success"], name="analytics_e_success_17cf4d_idx"
                    ),
                ],
            },
        ),
    ]
