# Generated by Django - Add timezone field to UsageAccount

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0011_executionlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="usageaccount",
            name="timezone",
            field=models.CharField(
                default="America/Chicago",
                help_text="User's preferred timezone for date display",
                max_length=50,
            ),
        ),
    ]
