# Generated by Django - Convert publish_date_cst to publish_date (UTC DateTimeField)

from django.db import migrations, models
from datetime import datetime, time
import pytz


def convert_cst_date_to_utc(apps, schema_editor):
    """
    Convert publish_date_cst (DateField in CST) to publish_date (DateTimeField in UTC).

    Strategy: Since we only have a date (no time), assume midnight CST (00:00:00).
    pytz handles DST transitions automatically.
    """
    Post = apps.get_model('analytics', 'Post')
    cst_tz = pytz.timezone('America/Chicago')

    for post in Post.objects.all():
        if post.publish_date_cst:
            # Create a naive datetime at midnight on the publish date
            naive_dt = datetime.combine(post.publish_date_cst, time.min)
            # Localize to CST (handles DST automatically)
            local_dt = cst_tz.localize(naive_dt)
            # Convert to UTC
            post.publish_date = local_dt.astimezone(pytz.UTC)
            post.save(update_fields=['publish_date'])


def reverse_utc_to_cst(apps, schema_editor):
    """Reverse migration: convert UTC datetime back to CST date."""
    Post = apps.get_model('analytics', 'Post')
    cst_tz = pytz.timezone('America/Chicago')

    for post in Post.objects.all():
        if post.publish_date:
            local_dt = post.publish_date.astimezone(cst_tz)
            post.publish_date_cst = local_dt.date()
            post.save(update_fields=['publish_date_cst'])


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0012_add_user_timezone"),
    ]

    operations = [
        # Step 1: Add the new publish_date DateTimeField
        migrations.AddField(
            model_name="post",
            name="publish_date",
            field=models.DateTimeField(
                blank=True,
                null=True,
                help_text="When the post was published (stored in UTC)",
            ),
        ),

        # Step 2: Data migration - convert existing CST dates to UTC
        migrations.RunPython(convert_cst_date_to_utc, reverse_utc_to_cst),

        # Step 3: Remove old index (must be done before removing field)
        # Note: Index was renamed in 0002 from analytics_p_publish_d47c8a_idx to analytics_p_publish_2615cc_idx
        migrations.RemoveIndex(
            model_name="post",
            name="analytics_p_publish_2615cc_idx",
        ),

        # Step 4: Remove old field
        migrations.RemoveField(
            model_name="post",
            name="publish_date_cst",
        ),

        # Step 5: Add new index
        migrations.AddIndex(
            model_name="post",
            index=models.Index(fields=["-publish_date"], name="analytics_p_publish_utc_idx"),
        ),

        # Step 6: Update ordering
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["-publish_date"]},
        ),
    ]
