# Generated by Django 5.2.9 on 2026-01-28 02:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0015_encrypt_existing_tokens"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SurveyResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "beehiiv_analytics_inadequate",
                    models.BooleanField(
                        help_text="Does the user feel Beehiiv analytics are inadequate?",
                        null=True,
                    ),
                ),
                (
                    "missing_features",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="What analytics features does the user feel are missing from Beehiiv?",
                    ),
                ),
                (
                    "other_tools",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="What other third-party tools does the user use for newsletter analytics?",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Survey Response",
                "verbose_name_plural": "Survey Responses",
            },
        ),
        migrations.RenameIndex(
            model_name="post",
            new_name="analytics_p_publish_1d9537_idx",
            old_name="analytics_p_publish_utc_idx",
        ),
        migrations.AddField(
            model_name="usageaccount",
            name="survey_completed",
            field=models.BooleanField(
                default=False,
                help_text="Whether the user has completed the signup survey",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="status",
            field=models.CharField(
                default="Published",
                help_text="Draft, Scheduled, or Published",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="surveyresponse",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="survey_response",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
