# Generated by Django 5.2.9 on 2026-02-18 22:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0019_report_decouple_and_pending_report"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pendingreport",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
