# Generated by Django 5.2.9 on 2026-02-20 22:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0020_alter_pendingreport_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="usageaccount",
            name="newsletter_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Name of the user's newsletter",
                max_length=255,
            ),
        ),
    ]
