# Generated by Django 5.2.9 on 2026-02-24 00:44

from django.db import migrations


def update_site(apps, schema_editor):
    Site = apps.get_model("sites", "Site")
    Site.objects.filter(pk=1).update(domain="letterpulse.com", name="LetterPulse")


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0021_add_newsletter_name_to_usageaccount"),
        ("sites", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(update_site, migrations.RunPython.noop),
    ]
