# Generated by Django 5.2.9 on 2026-02-26 01:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0022_update_site_domain"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="usageaccount",
            name="auto_click_viz_email",
            field=models.BooleanField(
                default=False,
                help_text="Whether to auto-email click visualizations after post publication",
            ),
        ),
        migrations.AddField(
            model_name="usageaccount",
            name="auto_click_viz_enabled_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the user enabled auto click viz emails; prevents old posts from triggering",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="ClickVizEmailLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "post_id",
                    models.CharField(help_text="Beehiiv post ID", max_length=255),
                ),
                (
                    "post_title",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                ("success", models.BooleanField(default=True)),
                ("error_message", models.TextField(blank=True, default="")),
                (
                    "publication",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="click_viz_email_logs",
                        to="analytics.publication",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="click_viz_email_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Click Viz Email Log",
                "verbose_name_plural": "Click Viz Email Logs",
                "ordering": ["-sent_at"],
                "unique_together": {("user", "post_id")},
            },
        ),
    ]
