# Generated by Django 5.2.9 on 2026-02-26 02:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0023_usageaccount_auto_click_viz_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usageaccount",
            name="auto_click_viz_delay_hours",
            field=models.PositiveIntegerField(
                default=6,
                help_text="Hours to wait after publication before sending click viz email (1-48)",
            ),
        ),
    ]
