# Generated by Django 5.2.9 on 2026-02-27 23:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0024_usageaccount_auto_click_viz_delay_hours"),
    ]

    operations = [
        migrations.CreateModel(
            name="CronRunLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "command",
                    models.CharField(
                        help_text="Management command name", max_length=255
                    ),
                ),
                ("started_at", models.DateTimeField(help_text="When the run started")),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True, help_text="When the run finished", null=True
                    ),
                ),
                (
                    "duration_ms",
                    models.PositiveIntegerField(
                        blank=True, help_text="Duration in milliseconds", null=True
                    ),
                ),
                ("users_processed", models.PositiveIntegerField(default=0)),
                ("emails_sent", models.PositiveIntegerField(default=0)),
                ("errors", models.PositiveIntegerField(default=0)),
                (
                    "output",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Captured stdout from the command",
                    ),
                ),
                ("success", models.BooleanField(default=True)),
                (
                    "triggered_by",
                    models.CharField(
                        default="cron",
                        help_text="How the run was triggered: cron, manual, etc.",
                        max_length=50,
                    ),
                ),
            ],
            options={
                "verbose_name": "Cron Run Log",
                "verbose_name_plural": "Cron Run Logs",
                "ordering": ["-started_at"],
            },
        ),
    ]
