# Generated by Django 5.2.9 on 2026-02-27 23:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0025_cronrunlog"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usageaccount",
            name="auto_click_viz_delay_hours",
        ),
    ]
