# Generated by Django 5.2.9 on 2026-03-02 02:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0026_remove_auto_click_viz_delay_hours"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usageaccount",
            name="auto_click_viz_email",
            field=models.BooleanField(
                default=True,
                help_text="Whether to auto-email click visualizations after post publication",
            ),
        ),
    ]
