# Generated by Django 5.2.9 on 2026-03-10 00:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0028_section_level_reports"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usageaccount",
            name="auto_click_viz_email",
            field=models.BooleanField(
                default=False,
                help_text="Whether to auto-email click visualizations after post publication",
            ),
        ),
    ]
