# Generated by Django 5.2.9 on 2026-03-25 03:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0029_auto_click_viz_email_default_false"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="processedpost",
            name="sections_data",
        ),
        migrations.CreateModel(
            name="LinkData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("raw_url", models.URLField(max_length=2048)),
                ("description", models.TextField(blank=True)),
                ("rank_in_post", models.PositiveIntegerField()),
                (
                    "mean_ctr",
                    models.FloatField(
                        help_text="Mean CTR as percentage (e.g. 3.5 = 3.5%)"
                    ),
                ),
                ("mean_clicks", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "post",
                    models.ForeignKey(
                        help_text="The post this link was extracted from",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="link_data",
                        to="analytics.post",
                    ),
                ),
                (
                    "publication",
                    models.ForeignKey(
                        blank=True,
                        help_text="The publication this link data belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="link_data",
                        to="analytics.publication",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user who owns this link data",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="link_data",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Link Data",
                "verbose_name_plural": "Link Data",
                "ordering": ["post", "rank_in_post"],
                "unique_together": {("post", "user", "raw_url")},
            },
        ),
        migrations.DeleteModel(
            name="ProcessingTemplate",
        ),
    ]
