# Generated by Django 5.2.9 on 2026-03-27 05:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0030_remove_processedpost_sections_data_linkdata_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("section_name", models.CharField(max_length=255)),
                ("section_description", models.TextField(blank=True)),
                ("start_line", models.PositiveIntegerField()),
                ("end_line", models.PositiveIntegerField()),
                (
                    "post_html_length",
                    models.PositiveIntegerField(
                        help_text="Total line count of the post HTML"
                    ),
                ),
                ("section_html", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "post",
                    models.ForeignKey(
                        help_text="The post this section was extracted from",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="analytics.post",
                    ),
                ),
                (
                    "publication",
                    models.ForeignKey(
                        blank=True,
                        help_text="The publication this section belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sections",
                        to="analytics.publication",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user who owns this section data",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Section",
                "verbose_name_plural": "Sections",
                "ordering": ["post", "start_line"],
                "unique_together": {("post", "user", "section_name")},
            },
        ),
    ]
