# Generated by Django 5.2.9 on 2026-03-28 18:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0031_section"),
    ]

    operations = [
        migrations.AddField(
            model_name="section",
            name="section_title",
            field=models.CharField(
                blank=True,
                help_text="Display title as it appears in the newsletter, or None if untitled",
                max_length=500,
                null=True,
            ),
        ),
    ]
