# Generated by Django 5.2.9 on 2026-04-01 21:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0032_section_section_title"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="linkdata",
            options={
                "ordering": ["post", "section_name", "rank_in_section"],
                "verbose_name": "Link Data",
                "verbose_name_plural": "Link Data",
            },
        ),
        migrations.AlterUniqueTogether(
            name="linkdata",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="linkdata",
            name="rank_in_section",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="linkdata",
            name="section_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name="linkdata",
            unique_together={("post", "user", "raw_url", "section_name")},
        ),
    ]
