# Generated by Django 5.2.9 on 2026-04-06 01:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0033_alter_linkdata_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="section",
            name="section_description",
        ),
    ]
