# Generated by Django 5.2.9 on 2026-04-10 22:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0037_feedback"),
    ]

    operations = [
        migrations.AddField(
            model_name="pendingcontentsearch",
            name="dev_panel_data",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="pendingimprovementtips",
            name="dev_panel_data",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
