# Generated by Django 5.2.9 on 2026-04-12 23:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0038_add_dev_panel_data"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentSearchFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("url", models.URLField(max_length=2000)),
                ("source", models.CharField(max_length=255)),
                ("pub_date", models.CharField(blank=True, default="", max_length=100)),
                ("description", models.TextField(blank=True, default="")),
                ("relevance", models.TextField(blank=True, default="")),
                (
                    "feedback",
                    models.CharField(
                        choices=[("up", "Thumbs Up"), ("down", "Thumbs Down")],
                        max_length=4,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "publication",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="content_search_feedback",
                        to="analytics.publication",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_search_feedback",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Content Search Feedback",
                "verbose_name_plural": "Content Search Feedback",
                "ordering": ["-created_at"],
                "unique_together": {("user", "publication", "url")},
            },
        ),
        migrations.DeleteModel(
            name="PendingReport",
        ),
    ]
