# Generated by Django 5.2.9 on 2026-04-19 22:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0041_post_platform"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PendingLearningTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_id", models.UUIDField(default=uuid.uuid4, unique=True)),
                (
                    "kind",
                    models.CharField(help_text="initial or update", max_length=10),
                ),
                (
                    "phase",
                    models.CharField(
                        default="fetch", help_text="fetch or process", max_length=10
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        default="pending",
                        help_text="pending, running, complete, error, or abandoned",
                        max_length=20,
                    ),
                ),
                (
                    "target_process_count",
                    models.IntegerField(
                        default=0,
                        help_text="Number of posts the process phase is expected to handle",
                    ),
                ),
                ("posts_processed_count", models.IntegerField(default=0)),
                ("error_message", models.TextField(blank=True)),
                ("abandoned", models.BooleanField(default=False)),
                ("last_heartbeat", models.DateTimeField(auto_now_add=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "publication",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="analytics.publication",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pending_learning_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "status"], name="analytics_p_user_id_a82d8a_idx"
                    )
                ],
            },
        ),
    ]
