# Generated by Django 5.2.9 on 2026-04-20 21:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0043_drop_contentset_report"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LLMCall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ts_start",
                    models.DateTimeField(help_text="When the LLM call was initiated"),
                ),
                (
                    "ts_end",
                    models.DateTimeField(
                        help_text="When the LLM call returned or errored"
                    ),
                ),
                (
                    "function_name",
                    models.CharField(
                        help_text="Logical function the call is for (e.g. 'content_finder')",
                        max_length=100,
                    ),
                ),
                (
                    "model",
                    models.CharField(help_text="OpenAI model name", max_length=100),
                ),
                ("input_tokens_cached", models.PositiveIntegerField(default=0)),
                ("input_tokens_new", models.PositiveIntegerField(default=0)),
                ("output_tokens_reasoning", models.PositiveIntegerField(default=0)),
                ("output_tokens_response", models.PositiveIntegerField(default=0)),
                ("success", models.BooleanField(default=True)),
                (
                    "error_type",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("error_message", models.TextField(blank=True, default="")),
                (
                    "task_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="UUID of the Pending* task that spawned this call, if any",
                        max_length=64,
                    ),
                ),
                (
                    "task_kind",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="e.g. 'content_finder', 'improvement_tips', 'learning_initial'",
                        max_length=50,
                    ),
                ),
                (
                    "additional_info",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Arbitrary call-specific metadata (e.g. section_name)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "publication",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="llm_calls",
                        to="analytics.publication",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="llm_calls",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-ts_start"],
                "indexes": [
                    models.Index(
                        fields=["-ts_start"], name="analytics_l_ts_star_82ca6a_idx"
                    ),
                    models.Index(
                        fields=["function_name"], name="analytics_l_functio_a500b5_idx"
                    ),
                    models.Index(
                        fields=["task_id"], name="analytics_l_task_id_0a0af5_idx"
                    ),
                    models.Index(
                        fields=["success"], name="analytics_l_success_d00a13_idx"
                    ),
                    models.Index(
                        fields=["user", "-ts_start"],
                        name="analytics_l_user_id_eea28b_idx",
                    ),
                ],
            },
        ),
    ]
