# Generated by Django 5.2.9 on 2026-04-23 02:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0044_llm_call"),
    ]

    operations = [
        migrations.AddField(
            model_name="pendingcontentsearch",
            name="dispatch_response_id",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="pendingcontentsearch",
            name="dispatch_sections",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="pendingcontentsearch",
            name="plan_response_id",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="pendingcontentsearch",
            name="plan_text",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="pendingcontentsearch",
            name="user_feedback",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="pendingcontentsearch",
            name="status",
            field=models.CharField(
                default="pending",
                help_text="pending, planning, awaiting_feedback, dispatching, searching, complete, or error",
                max_length=20,
            ),
        ),
    ]
