# Generated by Django 5.2.9 on 2026-04-23 20:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0045_pendingcontentsearch_dispatch_response_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pendingcontentsearch",
            name="dispatch_response_id",
        ),
        migrations.RemoveField(
            model_name="pendingcontentsearch",
            name="plan_response_id",
        ),
        migrations.AddField(
            model_name="pendingcontentsearch",
            name="dispatch_messages",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="pendingcontentsearch",
            name="plan_messages",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
