# Generated by Django 5.2.9 on 2026-04-29 00:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0047_alter_pendingcontentsearch_result_data"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PendingNicheAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_id", models.UUIDField(default=uuid.uuid4, unique=True)),
                (
                    "status",
                    models.CharField(
                        default="pending",
                        help_text="pending, running, complete, or error",
                        max_length=20,
                    ),
                ),
                ("niche", models.CharField(blank=True, default="", max_length=255)),
                ("content_types", models.JSONField(blank=True, default=list)),
                ("error_message", models.TextField(blank=True)),
                ("dev_panel_data", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "publication",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="analytics.publication",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pending_niche_analyses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Pending Niche Analysis",
                "verbose_name_plural": "Pending Niche Analyses",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "publication", "-created_at"],
                        name="analytics_p_user_id_df37f2_idx",
                    )
                ],
            },
        ),
    ]
