# Generated by Django 5.2.9 on 2026-05-12 21:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0051_drop_survey_and_cronrunlog"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pendinglearningtask",
            name="abandoned",
        ),
        migrations.AddField(
            model_name="pendingcontentsearch",
            name="credits_charged",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="pendingcontentsearch",
            name="last_heartbeat",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="pendingcontentsearch",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="pendingimprovementtips",
            name="credits_charged",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="pendingimprovementtips",
            name="last_heartbeat",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="pendingimprovementtips",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="pendinglearningtask",
            name="credits_charged",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="pendingnicheanalysis",
            name="credits_charged",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="pendingnicheanalysis",
            name="last_heartbeat",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="pendingnicheanalysis",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="pendingcontentsearch",
            name="error_message",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="pendingcontentsearch",
            name="status",
            field=models.CharField(default="pending", max_length=20),
        ),
        migrations.AlterField(
            model_name="pendingimprovementtips",
            name="error_message",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="pendingimprovementtips",
            name="status",
            field=models.CharField(default="pending", max_length=20),
        ),
        migrations.AlterField(
            model_name="pendinglearningtask",
            name="error_message",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="pendinglearningtask",
            name="last_heartbeat",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="pendinglearningtask",
            name="status",
            field=models.CharField(default="pending", max_length=20),
        ),
        migrations.AlterField(
            model_name="pendingnicheanalysis",
            name="error_message",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="pendingnicheanalysis",
            name="status",
            field=models.CharField(default="pending", max_length=20),
        ),
    ]
