# Generated by Django 5.2.9 on 2026-05-14 03:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0052_remove_pendinglearningtask_abandoned_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="linkdata",
            index=models.Index(
                fields=["user", "publication"], name="analytics_l_user_id_a3257f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="section",
            index=models.Index(
                fields=["user", "publication"], name="analytics_s_user_id_63f7a2_idx"
            ),
        ),
    ]
